//! Proof-of-work evidencing: pure helpers for the proof step.
//!
//! The proof session (a dedicated `claude` run in the worktree, after review passes) captures the
//! richest feasible evidence that the change *works* — a walkthrough video, screenshots, a terminal
//! cast, or (the floor) a grounded report with verbatim command output — so a human reviews the
//! output/functionality, not the diff. Media lands in a per-ticket artifact dir under `~/.harmony`
//! (never the repo); the prose report is captured from the session's plan-file write.
//!
//! This module holds only the *pure* pieces: classifying an artifact file, scanning the artifact
//! dir, and rendering the PR comment. The session spawn lives in [`crate::session`], the capture
//! hook in [`crate::hooks`], and the media hosting (`gh`) in [`crate::github`].

use serde::{Deserialize, Serialize};
use std::path::Path;

/// One captured evidence artifact.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProofArtifact {
    /// "image" | "video" | "cast" | "file" — how the UI/PR comment should render it.
    pub kind: String,
    /// Absolute local path under the ticket's artifact dir (served by the app for the Proof tab).
    pub path: String,
    /// Human caption (the file stem, cleaned up).
    pub caption: String,
    /// Teammate-reachable URL once hosted (empty until uploaded for the PR comment).
    #[serde(default)]
    pub url: String,
}

/// Classify an artifact file by extension into a render kind.
pub fn kind_for(path: &str) -> &'static str {
    let ext = Path::new(path)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_ascii_lowercase();
    match ext.as_str() {
        "png" | "jpg" | "jpeg" | "gif" | "webp" => "image",
        "mp4" | "webm" | "mov" | "m4v" => "video",
        "cast" => "cast",
        _ => "file",
    }
}

/// A readable caption from a filename: strip the extension, replace separators with spaces.
fn caption_for(path: &str) -> String {
    let stem = Path::new(path)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("artifact");
    stem.replace(['_', '-'], " ")
}

/// Scan a proof artifact dir into a sorted list of [`ProofArtifact`]s (by filename, so images order
/// deterministically). Non-recursive; ignores dotfiles. Returns empty when the dir is missing/empty.
pub fn scan_artifacts(dir: &str) -> Vec<ProofArtifact> {
    let mut entries: Vec<ProofArtifact> = Vec::new();
    let read = match std::fs::read_dir(dir) {
        Ok(r) => r,
        Err(_) => return entries,
    };
    for e in read.flatten() {
        if !e.file_type().map(|t| t.is_file()).unwrap_or(false) {
            continue;
        }
        let name = e.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        let path = e.path().to_string_lossy().to_string();
        entries.push(ProofArtifact {
            kind: kind_for(&path).to_string(),
            caption: caption_for(&path),
            path,
            url: String::new(),
        });
    }
    entries.sort_by(|a, b| a.path.cmp(&b.path));
    entries
}

/// Render the PR comment body from the proof report and the (hosted) artifacts. Images embed inline
/// (they render from their hosted URLs); videos/casts/files are linked. Artifacts without a URL
/// (hosting failed / disabled) are noted as available in harmony. A trailing marker lets us find +
/// update our own comment later.
pub fn render_pr_comment(report: &str, artifacts: &[ProofArtifact]) -> String {
    let mut out = String::from("## 🔎 Proof of work\n\n");
    out.push_str(
        "_Generated by harmony — review the output/functionality below rather than the diff._\n\n",
    );

    let (mut images, mut media, mut local) = (Vec::new(), Vec::new(), Vec::new());
    for a in artifacts {
        if a.url.is_empty() {
            local.push(a);
        } else if a.kind == "image" {
            images.push(a);
        } else {
            media.push(a);
        }
    }

    for a in &images {
        out.push_str(&format!("![{}]({})\n\n", a.caption, a.url));
    }
    for a in &media {
        let icon = if a.kind == "video" { "🎥" } else { "📄" };
        out.push_str(&format!("{icon} [{}]({})\n\n", a.caption, a.url));
    }

    let report = report.trim();
    if !report.is_empty() {
        out.push_str(report);
        out.push('\n');
    }

    if !local.is_empty() {
        out.push_str(&format!(
            "\n_{} additional artifact(s) available in harmony's Proof tab._\n",
            local.len()
        ));
    }

    out.push_str("\n<!-- harmony:proof -->\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn art(kind: &str, caption: &str, url: &str) -> ProofArtifact {
        ProofArtifact {
            kind: kind.into(),
            path: format!("/tmp/{caption}"),
            caption: caption.into(),
            url: url.into(),
        }
    }

    #[test]
    fn kinds_by_extension() {
        assert_eq!(kind_for("/a/b/shot.PNG"), "image");
        assert_eq!(kind_for("demo.mp4"), "video");
        assert_eq!(kind_for("run.cast"), "cast");
        assert_eq!(kind_for("notes.txt"), "file");
        assert_eq!(kind_for("noext"), "file");
    }

    #[test]
    fn caption_cleans_filename() {
        assert_eq!(caption_for("/x/tag_filter-demo.png"), "tag filter demo");
    }

    #[test]
    fn comment_embeds_images_links_video_and_notes_local() {
        let arts = vec![
            art("image", "before", "https://x/before.png"),
            art("video", "walkthrough", "https://x/demo.mp4"),
            art("image", "local-shot", ""),
        ];
        let body = render_pr_comment("**What works:** filtering.", &arts);
        assert!(body.contains("![before](https://x/before.png)"));
        assert!(body.contains("🎥 [walkthrough](https://x/demo.mp4)"));
        assert!(body.contains("What works:** filtering."));
        assert!(body.contains("1 additional artifact"));
        assert!(body.contains("<!-- harmony:proof -->"));
    }

    #[test]
    fn comment_without_artifacts_is_just_report() {
        let body = render_pr_comment("report body", &[]);
        assert!(body.contains("report body"));
        assert!(!body.contains("additional artifact"));
    }
}
